apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2 # must match the selector above to link the Deployment to the Pods
    spec:
      containers:
        - name: service-2
          image: romany/service-2:0.0.1
          env:
            - name: SERVICE_1_URL
              value: "http://service-1-svc:3000"  # URL to access service-1 within the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: service-2-svc
spec: 
  type: ClusterIP
  selector:
    app: service-2  # must match the label in the Pod template above to link the Service to the Pods
  ports:
    - name: service-2-http
      protocol: TCP
      port: 5001  # External port (what other services call)
      targetPort: 5001 # Internal port (what the container listens on)
  
