apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-1
  template:
      metadata:
        labels:
          app: service-1
      spec:
         containers:
            - name: service-1
              image: romany/service-1:0.0.1
              env:
                - name: SERVICE_2_URL
                  value: "http://service-2-svc:5001"  # URL to access service-2 within the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: service-1-svc
spec:
  type: ClusterIP # Cluster-internal service (default)
  selector:
    app: service-1
  ports:
    - name: service-1-http  
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-1-nodeport-svc
spec:
  type: NodePort # Exposes the service on each Node's IP at a static port (the NodePort)
  selector:
    app: service-1
  ports:
    - name: service-1-http   
      protocol: TCP
      port: 3000
      targetPort: 3000
